// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'app_widget.dart';

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: b0Builder,
      ),
      RouteEntity(
        key: '/search',
        uri: Uri.parse('/search'),
        routeBuilder: b1Builder,
      ),
      RouteEntity(
        key: '/detailed',
        uri: Uri.parse('/detailed'),
        routeBuilder: b2Builder,
      ),
    ];

const routePaths = (
  path: '/',
  home: '/home',
  search: '/search',
  detailed: '/detailed',
);
